### ISSUE TITLE
User Story 18 Configure environment variables 

### ISSUE THREAD

**Issue by JorgenDIF** [JorgenDIF/PP5-RestInEase-API#21]
As a **developer**, I want to **configure environment variables and dependencies to connect the frontend and backend**, so that **they can communicate securely**.

**Acceptance Criteria:**

1. Environment variables are set up correctly for both frontend and backend.
2. All necessary dependencies are installed and configured.

**Tasks:**

- [ ] Configure environment variables in the frontend and backend.
- [ ] Install and configure any necessary dependencies for secure communication.
- [ ] Verify the connection between frontend and backend.
