### ISSUE TITLE
User Story 20 Mentor Session 2

### ISSUE THREAD

**Issue by JorgenDIF** [JorgenDIF/PP5-RestInEase-API#22]
As a **developer**, I want to **review the integrated system with my mento**r, so that I can **get feedback and improve the integration**.

**Acceptance Criteria:**

1. Mentor feedback is documented and discussed.
2. Necessary adjustments are made based on feedback.

**Tasks:**

- [x] Schedule and conduct the mentor meeting.
- [ ] Present the integrated system.
- [ ] Document and address mentor feedback.
