### ISSUE TITLE
User Story 24 Code Validation

### ISSUE THREAD

**Issue by JorgenDIF** [JorgenDIF/PP5-RestInEase-API#26]
As a **developer,** I want to **validate and manually test the React, CSS,  and Python code,** so that it **adheres to web standards and functions correctly**.

**Acceptance Criteria:**

1. React,HTML and CSS code is validated using appropriate tools.
2. Python code is manually tested for key functionalities.
3. Any validation errors or issues found are documented and resolved.

**Tasks:**

- [x] Use ESLint to test React code.
- [x] Use CSS validator to check CSS code.
- [x] Use HTML validator to check HTML code.
- [x] Test Django views and models manually using the Django admin and shell.
- [x] Document and fix any validation errors or issues found during manual testing.
