### ISSUE TITLE
User Story 28 Final Test

### ISSUE THREAD

**Issue by JorgenDIF** [JorgenDIF/PP5-RestInEase-API#30]
As a **developer**, I want to **perform a comprehensive test of the deployed application**, so that I can **ensure everything works as expected**.

**Acceptance Criteria:**

1. Comprehensive tests are performed and pass successfully.

**Tasks:**

- [x] Perform end-to-end testing in the production environment.
- [x] Verify all functionalities and features.
- [x] Fix any issues found during testing.
