### ISSUE TITLE
User Story 29 Final Mentor Session

### ISSUE THREAD

**Issue by JorgenDIF** [JorgenDIF/PP5-RestInEase-API#31]
As a **developer**, I want to **present the deployed application to my mentor**, so that I can **get feedback and make any necessary adjustments**.

**Acceptance Criteria:**

1. Mentor feedback is documented and discussed.
2. Necessary adjustments are made based on feedback.

**Tasks:**

- [x] Schedule and conduct the mentor meeting.
- [x] Present the deployed application.
- [x] Document and address mentor feedback.
