### ISSUE TITLE
User Story 5 Wireframes and Logo

### ISSUE THREAD

**Issue by JorgenDIF** [JorgenDIF/PP5-RestInEase-API#6]
As a **developer**, I want to **create wireframes for the key pages**, so that **the user interface is planned and user-friendly.**

**Acceptance Criteria:**

1. Wireframes for all key pages are created.
2. Logo created

**Tasks:**

- [x] Design wireframes for each key page.
- [x] Include a task to design the application logo.
- [x] Review and refine wireframes based on feedback.
