### ISSUE TITLE
User Story 6 Mentors Review

### ISSUE THREAD

**Issue by JorgenDIF** [JorgenDIF/PP5-RestInEase-API#7]
As a developer, I want to present my ERD, wireframes, and project plan to my mentor, so that I can get feedback, ensure the plan is feasible, and improve the design.

**Acceptance Criteria:**

1. Mentor feedback is documented and discussed.
2. Project plan is reviewed and adjusted based on mentor feedback.

**Tasks:**

- [ ] Prepare ERD, wireframes, and project plan for presentation.
- [ ] Schedule and conduct the mentor meeting.
- [ ] Incorporate mentor’s suggestions into the project plan.
